M48
; DRILL file {KiCad 7.0.5-0} date 2024 February 02, Friday 13:20:01
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-02T13:20:01-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.889
%
G90
G05
T1
X112.4Y-65.708
X112.4Y-71.488
T2
X106.76Y-77.455
X113.56Y-77.455
T0
M30
